// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace dropasp {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl body1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox apiKeyTextBox;
		
		protected System.Web.UI.WebControls.TextBox apiSecretTextBox;
		
		protected System.Web.UI.WebControls.Button findDropsButton;
		
		protected System.Web.UI.WebControls.DropDownList dropsList;
		
		protected System.Web.UI.WebControls.Button getDropButton;
		
		protected System.Web.UI.WebControls.Button createDropButton;
		
		protected System.Web.UI.WebControls.MultiView multiView1;
		
		protected System.Web.UI.WebControls.View emptyView;
		
		protected System.Web.UI.WebControls.View dropView;
		
		protected System.Web.UI.WebControls.Table dropViewTable;
		
		protected System.Web.UI.WebControls.TableCell dropName;
		
		protected System.Web.UI.WebControls.TableCell dropEmail;
		
		protected System.Web.UI.WebControls.TableCell dropNumberOfAssets;
		
		protected System.Web.UI.WebControls.TableCell dropCurrentSize;
		
		protected System.Web.UI.WebControls.TableCell dropMaxSize;
		
		protected System.Web.UI.WebControls.TableCell dropDescription;
		
		protected System.Web.UI.WebControls.TableCell dropChatPassword;
		
		protected System.Web.UI.WebControls.Button viewAssetsButton;
		
		protected System.Web.UI.WebControls.DropDownList assetsPage;
		
		protected System.Web.UI.WebControls.DropDownList assetsOrder;
		
		protected System.Web.UI.WebControls.Button addAssetButton;
		
		protected System.Web.UI.WebControls.Button emptyDropButton;
		
		protected System.Web.UI.WebControls.Button destroyDropButton;
		
		protected System.Web.UI.WebControls.View assetListView;
		
		protected System.Web.UI.WebControls.View singleAssetView;
		
		protected System.Web.UI.WebControls.View addAssetView;
		
		protected System.Web.UI.WebControls.Label dropNameLabel;
		
		protected System.Web.UI.WebControls.TextBox assetDescriptionTextBox;
		
		protected System.Web.UI.WebControls.CheckBox assetDefaultConversionCheckBox;
		
		protected System.Web.UI.WebControls.TextBox assetPingbackUrlTextBox;
		
		protected System.Web.UI.WebControls.TextBox assetOutputLocationsTextBox;
		
		protected System.Web.UI.HtmlControls.HtmlInputFile file;
		
		protected System.Web.UI.WebControls.View createDropView;
		
		protected System.Web.UI.WebControls.TextBox createDropName;
		
		protected System.Web.UI.WebControls.TextBox createDropDescription;
		
		protected System.Web.UI.WebControls.TextBox createDropEmailKey;
		
		protected System.Web.UI.WebControls.TextBox createDropMaxSize;
		
		protected System.Web.UI.WebControls.TextBox createDropChatPassword;
		
		protected System.Web.UI.WebControls.Button createDropGo;
		
		protected System.Web.UI.WebControls.View deleteAssetView;
		
		protected System.Web.UI.WebControls.Label areYouSureLabel;
		
		protected System.Web.UI.WebControls.View assetGridView;
		
		protected System.Web.UI.WebControls.GridView gridview1;
		
		protected System.Web.UI.WebControls.ObjectDataSource ObjectDataSource1;
	}
}
